name: Layotto Java SDK Dev Pipeline 🌊

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: "*"
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  build:
    #	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # 下载代码
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        # 安装 JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      # Maven 打包
      - name: Build with Maven
        run: cd examples-preview-service && mvn -B package --file pom.xml
      # 将打包好的 Jar 包 放到 staging 文件夹
      - run: ls && cp examples-preview-service/target/*.jar docker/preview_server


